using System.Text.Json.Serialization;
using GestorOT.Shared.Dtos;

namespace GestorOT.Shared;

[JsonSerializable(typeof(FieldDto))]
[JsonSerializable(typeof(List<FieldDto>))]
[JsonSerializable(typeof(LotDto))]
[JsonSerializable(typeof(List<LotDto>))]
[JsonSerializable(typeof(LotSummaryDto))]
[JsonSerializable(typeof(List<LotSummaryDto>))]
[JsonSerializable(typeof(WorkOrderDto))]
[JsonSerializable(typeof(List<WorkOrderDto>))]
[JsonSerializable(typeof(RecentWorkOrderDto))]
[JsonSerializable(typeof(List<RecentWorkOrderDto>))]
[JsonSerializable(typeof(GeoJsonFeature))]
[JsonSerializable(typeof(List<GeoJsonFeature>))]
[JsonSerializable(typeof(GeoJsonGeometry))]
[JsonSerializable(typeof(GeoJsonFeatureCollection))]
[JsonSerializable(typeof(DashboardStatsDto))]
[JsonSerializable(typeof(InventoryDto))]
[JsonSerializable(typeof(List<InventoryDto>))]
[JsonSerializable(typeof(LaborDto))]
[JsonSerializable(typeof(List<LaborDto>))]
[JsonSerializable(typeof(LaborSupplyDto))]
[JsonSerializable(typeof(List<LaborSupplyDto>))]
[JsonSerializable(typeof(WorkOrderDetailDto))]
[JsonSerializable(typeof(List<WorkOrderDetailDto>))]
[JsonSerializable(typeof(CropStrategyDto))]
[JsonSerializable(typeof(List<CropStrategyDto>))]
[JsonSerializable(typeof(StrategyItemDto))]
[JsonSerializable(typeof(List<StrategyItemDto>))]
[JsonSerializable(typeof(StrategySupplyDefault))]
[JsonSerializable(typeof(List<StrategySupplyDefault>))]
[JsonSerializable(typeof(ApplyStrategyRequest))]
[JsonSerializable(typeof(ApplyStrategyResult))]
[JsonSerializable(typeof(EmployeeDto))]
[JsonSerializable(typeof(List<EmployeeDto>))]
[JsonSerializable(typeof(LaborTypeDto))]
[JsonSerializable(typeof(List<LaborTypeDto>))]
[JsonSerializable(typeof(DiscrepancyReportDto))]
[JsonSerializable(typeof(LaborDiscrepancyDto))]
[JsonSerializable(typeof(SupplyDiscrepancyDto))]
[JsonSerializable(typeof(TenantDto))]
[JsonSerializable(typeof(List<TenantDto>))]
[JsonSerializable(typeof(CreateTenantRequest))]
[JsonSerializable(typeof(UpdateTenantRequest))]
[JsonSerializable(typeof(ShareLinkDto))]
[JsonSerializable(typeof(PublicWorkOrderDto))]
[JsonSerializable(typeof(PublicLaborDto))]
[JsonSerializable(typeof(List<PublicLaborDto>))]
[JsonSerializable(typeof(PublicLaborSupplyDto))]
[JsonSerializable(typeof(List<PublicLaborSupplyDto>))]
[JsonSerializable(typeof(UserProfileDto))]
[JsonSerializable(typeof(List<UserProfileDto>))]
[JsonSerializable(typeof(TankMixRuleDto))]
[JsonSerializable(typeof(List<TankMixRuleDto>))]
[JsonSerializable(typeof(TankMixAlertDto))]
[JsonSerializable(typeof(List<TankMixAlertDto>))]
[JsonSerializable(typeof(AuditLogDto))]
[JsonSerializable(typeof(List<AuditLogDto>))]
[JsonSerializable(typeof(TankMixValidationRequest))]
[JsonSerializable(typeof(CampaignDto))]
[JsonSerializable(typeof(List<CampaignDto>))]
[JsonSerializable(typeof(CampaignFieldDto))]
[JsonSerializable(typeof(List<CampaignFieldDto>))]
[JsonSerializable(typeof(CampaignSummaryDto))]
[JsonSerializable(typeof(List<CampaignSummaryDto>))]
[JsonSerializable(typeof(LaborCalendarDto))]
[JsonSerializable(typeof(List<LaborCalendarDto>))]
[JsonSerializable(typeof(CampaignLotDto))]
[JsonSerializable(typeof(List<CampaignLotDto>))]
[JsonSerializable(typeof(ImportLotsRequest))]
[JsonSerializable(typeof(CampaignStatus))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Default)]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}
